### ISSUE TITLE
Strange data in Aggregate's component versions requirements table

### ISSUE THREAD

**Issue by ehbossa** [getodk/docs#1185]
In:
https://docs.opendatakit.org/aggregate-deployment-planning/

At:
https://docs.opendatakit.org/aggregate-deployment-planning/#component-versions

On the table header row, the left cell is empty and the right one contains "**≥ v1.4.13**".

At least to me, it is not clear the meaning of that:

![Aggregate's component versions requirements table](https://user-images.githubusercontent.com/18150289/76166533-8aff5c80-615f-11ea-90fe-0605fe0d71ac.png)

**Comment by lognaturel** [comment]
Hi @ehbossa! In general, it's ideal to post questions to https://forum.opendatakit.org/c/support/6 because more people see them and can benefit.

The left column refers to components. Perhaps we should add a "Component" heading? There is only one column of versions because required versions were only documented starting with Aggregate version v1.4.13. Those version requirements have not changed since. Let's say that a new v3.2.1 required Java 16, we'd add another column to the right to document that.

Does that help?
