### ISSUE TITLE
When opening a blank form after a crash, Collect restores a savepoint

### ISSUE THREAD

**Issue by lognaturel** [getodk/docs#1463]
This is implicit and confusing: https://github.com/getodk/collect/issues/3494

**Comment by lognaturel** [comment]
Link from https://github.com/getodk/docs/pull/1735/files#diff-ec1d9db1ea171989fd7a324cbd1bd1c5d119ac88348f26f602d639fd3746fa68R184

**Comment by lognaturel** [comment]
- Users are now explicitly prompted to restore from savepoint
- Savepoints from older form versions can be restored from, they are opened with the form version they were created with
- When you've restored from a savepoint, you can discard changes as you normally could, there is then no way to recover savepoint data
- A savepoint is saved when minimizing the app, on crash, device shutdown

**Comment by seadowg** [comment]
@lognaturel a couple of things to maybe add:

- If you have a save point from an older version of the form and discard it, you will still open the requested version of the form (rather than the older version that the save point was for)
- If you have a save point for a newer version of the form (you've disabled "Hide old versions" and have clicked on an old form version or are using an external app), you won't be offered to restore work (but will be if you open the newer version with the save point).

This part is also not quite right:

> A savepoint is saved when minimizing the app, on crash, device shutdown


We create a save point in three scenarios:
- When you change screens (via next/back or swiping)
- When you switch to another app - older Android would be "minimize", but newer versions don't call `onSaveInstanceState` until you actually switch to another app

We don't create a save point on crash, but I think we will usually get one if the user shuts down or restarts.
