### ISSUE TITLE
Update entities via submission

### ISSUE THREAD

**Issue by matthew-white** [getodk/docs#1678]
This issue is to document the new functionality described in the v2023.5 [release criteria](https://docs.google.com/document/d/1EdEDcXoJmrryFYNc56zciuQ82G_iVGBQf1UFEkWiUtw/edit?usp=share_link).

**Comment by ktuite** [comment]
Here's a first pass at interesting topics to cover:

## New things to know about form design

- [ ] Update forms now possible: submissions can update entities
- [ ] Update forms can modify entity lists (add new properties)
- [ ] What data can be updated on an entity?
    * label
        * if not included or set to blank, update will be ignored / label will not be updated
    * property
        * if not included, update of this property will be ignored 
        * if set to blank, property will be updated to empty
- [ ] Create or update in a single form

## New things to know about entities

- [ ] Entities have version numbers now... numbered starting with 1, new version for each update. Version number assigned by Central when update occurs.
- [ ] Entities can now have conflicts/be in conflict, which means updates are continuing to be applied but a someone should check the entity's data to make sure it makes sense because two people might have tried to update it at the same time.

## Conflicts (seemed like they should be their own category)

- [ ] soft conflicts
- [ ] hard conflicts
- [ ] what does it mean to "resolve" a conflict?
- [ ] author's view vs. central's view

## Etcetera 

- [ ] Types of errors: 
    * uuid doesn't exist when performing an update
    * base version doesn't exist [NOTE: if the base version specified doesn't exist, i think it fails to process the entity but it could also count as a conflict. something we talked about relative to offline entities at one point, if you cant figure out the right base version, send 0 or something??]
- [ ] Editing a submission that has already made or update an entity doesn't change the entity... a submission only has 1 chance to affect an entity
- [ ] Could have a conditional update field, edit a submission to trigger the entity update.

**Comment by ktuite** [comment]
I was trying to tell a [forum user](https://forum.getodk.org/t/how-to-avoid-duplicate-entity-record-from-follow-up-form/43979/2) about `create_if` and realized there's very little in our docs about conditional create (and soon to be conditional update).

I only found `create_if` in the XLSForm template and in the [ODK spec proposal](https://docs.google.com/document/d/1-O_wT0JZZFaWvzHl_krrzERJcnrdGMKP55ZZ_hxV0gU/edit?usp=sharing) document.
